/**
 *  Purpose         :   This class is to hold the Prodly Moover app constants
 * 
 *  Created Date    :   03/24/2017
 * 
 *  Created By      :   Romesh Kumar
 * 
 *  Current Version :   V_1.0
 **/
public class ProdlyConstants {
    
    /* Constant using on Deployment Result on 3/24/2017 */
    public final static String STARTED = 'Started';
    public final static String PAUSED = 'Paused';
    public final static String STOPPED = 'Stopped';
    public final static String FINISHED = 'Finished';
    public final static String DEPLOYMENT_SERVICE_SUCCESS_MESSAGE = 'Request has been submitted successfully. It will get finshed with in a minute.';
    public final static String WEB_SERVICE_URL = 'http://prodly-moover-dev.herokuapp.com';
    public final static String RESUME_REQUEST = 'Resume';
    public final static String PAUSE_REQUEST = 'Pause';
    public final static String STOP_REQUEST = 'Stop';

}